// Generated by openapi-to-zod — do NOT edit manually
import { z } from 'zod'

export const ErrorEnvelopeSchema = z.object({ "success": z.literal(false), "error": z.string() })

export const HealthDataSchema = z.object({ "status": z.literal("ok"), "ts": z.string().datetime({ offset: true }) })
