// Generated by openapi-to-zod — do NOT edit manually
import type { z } from 'zod'
import { ErrorEnvelopeSchema, HealthDataSchema } from './schemas'

export type ErrorEnvelope = z.infer<typeof ErrorEnvelopeSchema>
export type HealthData = z.infer<typeof HealthDataSchema>
