// Generated by openapi-to-zod — do NOT edit manually
import type { z } from 'zod'
import { BandSchema, ErrorEnvelopeSchema, EventDetailSchema, EventSiblingSchema, HealthDataSchema, IngestBatchSchema, IngestCountsSchema, IngestEventSchema, IngestPlaceSchema, IngestRejectionSchema, IngestResultSchema, IntentSchema, ItemKindSchema, MusicGenreSchema, OpeningPeriodSchema, PlaceDetailSchema, PlaceKindSchema, PlaceOfferSchema, PlaceOriginSchema, PlaceRefSchema, PriceStatusSchema, SearchItemSchema, SearchPinSchema, SourceLinkSchema, SourceTierSchema, TimeOfDaySchema, UpcomingEventSchema, ZoneSchema } from './schemas'

export type Band = z.infer<typeof BandSchema>
export type ErrorEnvelope = z.infer<typeof ErrorEnvelopeSchema>
export type EventDetail = z.infer<typeof EventDetailSchema>
export type EventSibling = z.infer<typeof EventSiblingSchema>
export type HealthData = z.infer<typeof HealthDataSchema>
export type IngestBatch = z.infer<typeof IngestBatchSchema>
export type IngestCounts = z.infer<typeof IngestCountsSchema>
export type IngestEvent = z.infer<typeof IngestEventSchema>
export type IngestPlace = z.infer<typeof IngestPlaceSchema>
export type IngestRejection = z.infer<typeof IngestRejectionSchema>
export type IngestResult = z.infer<typeof IngestResultSchema>
export type Intent = z.infer<typeof IntentSchema>
export type ItemKind = z.infer<typeof ItemKindSchema>
export type MusicGenre = z.infer<typeof MusicGenreSchema>
export type OpeningPeriod = z.infer<typeof OpeningPeriodSchema>
export type PlaceDetail = z.infer<typeof PlaceDetailSchema>
export type PlaceKind = z.infer<typeof PlaceKindSchema>
export type PlaceOffer = z.infer<typeof PlaceOfferSchema>
export type PlaceOrigin = z.infer<typeof PlaceOriginSchema>
export type PlaceRef = z.infer<typeof PlaceRefSchema>
export type PriceStatus = z.infer<typeof PriceStatusSchema>
export type SearchItem = z.infer<typeof SearchItemSchema>
export type SearchPin = z.infer<typeof SearchPinSchema>
export type SourceLink = z.infer<typeof SourceLinkSchema>
export type SourceTier = z.infer<typeof SourceTierSchema>
export type TimeOfDay = z.infer<typeof TimeOfDaySchema>
export type UpcomingEvent = z.infer<typeof UpcomingEventSchema>
export type Zone = z.infer<typeof ZoneSchema>
