// Aggregates openapi-to-zod per-schema files into packages/shared/src/schemas.ts
// and derives packages/shared/src/types.ts via z.infer<>.
// Run via: npm run generate:schemas
import { execSync } from 'child_process'
import { readdir, readFile, writeFile, rm, mkdir } from 'fs/promises'
import { join } from 'path'

const TMP_DIR = 'packages/shared/src/.zod-tmp'
const SCHEMAS_OUT = 'packages/shared/src/schemas.ts'
const TYPES_OUT = 'packages/shared/src/types.ts'

await mkdir(TMP_DIR, { recursive: true })

execSync(`npx openapi-to-zod -i docs/api-spec.yml -o ${TMP_DIR} -x ts`, { stdio: 'inherit' })

const files = (await readdir(TMP_DIR)).filter(f => f.endsWith('.ts')).sort()

const schemaLines = [
  '// Generated by openapi-to-zod — do NOT edit manually',
  "import { z } from 'zod'",
  '',
]
const typeImportNames = []
const typeExportLines = []

for (const file of files) {
  const schemaName = file.replace(/^zod-/, '').replace(/\.ts$/, '')
  const exportName = `${schemaName}Schema`
  const raw = await readFile(join(TMP_DIR, file), 'utf8')
  const expr = raw
    .replace(/^import \{ z \} from "zod";\n+export default /, '')
    .trimEnd()
    .replace(/;$/, '')

  schemaLines.push(`export const ${exportName} = ${expr}`)
  schemaLines.push('')
  typeImportNames.push(exportName)
  typeExportLines.push(`export type ${schemaName} = z.infer<typeof ${exportName}>`)
}

const typeLines = [
  '// Generated by openapi-to-zod — do NOT edit manually',
  "import type { z } from 'zod'",
  `import { ${typeImportNames.join(', ')} } from './schemas'`,
  '',
  ...typeExportLines,
  '',
]

await writeFile(SCHEMAS_OUT, schemaLines.join('\n'))
await writeFile(TYPES_OUT, typeLines.join('\n'))
await rm(TMP_DIR, { recursive: true })

console.log(`✓ ${SCHEMAS_OUT}`)
console.log(`✓ ${TYPES_OUT}`)
